CREATE TABLE IF NOT EXISTS tblMercadorias(
	codigo BIGINT NOT NULL AUTO_INCREMENT,
    tipo VARCHAR(50) NOT NULL,
    nm VARCHAR(60) NOT NULL,
    qtd INT NOT NULL DEFAULT '0',
    preco DECIMAL(4,2) NOT NULL,
    tp_negocio CHAR(6) NOT NULL,
    CONSTRAINT PK_CODIGO PRIMARY KEY(codigo)
);

CREATE TABLE IF NOT EXISTS tblNews(
	id BIGINT NOT NULL AUTO_INCREMENT,
    nm VARCHAR(30) NOT NULL,
    email VARCHAR(80) NOT NULL,
    CONSTRAINT PK_ID_NEWS PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS `tblUsrs`(
	id BIGINT NOT NULL AUTO_INCREMENT,
    nm VARCHAR(50) NOT NULL,
    email VARCHAR(767) NOT NULL,
    pwd VARCHAR(767) NOT NULL,
    ativo TINYINT NOT NULL DEFAULT '1',
    CONSTRAINT PK_ID_USR PRIMARY KEY(id)
);
